MYBUSINESS/Controllers/StockTransectionsController.cs
using MYBUSINESS.CustomClasses;
using MYBUSINESS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MYBUSINESS.Controllers
{
    public class StockTransectionsController : Controller
    {
        private BusinessContext db = new BusinessContext();
        private DAL DAL = new DAL();
        //[NoCache]
        public ActionResult Summary()
        {

            DateTime PKDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Pakistan Standard Time"));
            var dtStartDate = new DateTime(PKDate.Year, PKDate.Month, 1);
            var dtEndtDate = dtStartDate.AddMonths(1).AddSeconds(-1);

            
            ViewBag.Customers = DAL.dbCustomers;
           

            ViewBag.StartDate = dtStartDate.ToString("dd-MMM-yyyy");
            ViewBag.EndDate = dtEndtDate.ToString("dd-MMM-yyyy");

            
            DashboardViewModel dbVM = new DashboardViewModel();
            
            List<SOD> FilteredSaleOrderDetails;// = db.Customers;
            List<POD> FilteredPurchaseOrderDetails;// = db.Customers;
            List<Product> FilteredProducts = new List<Product>();
            foreach (Product prod in db.Products)
            {
                
                FilteredSaleOrderDetails = new List<SOD>();

                foreach (SOD sod in prod.SODs)
                {
                    if (sod.SO.Date >= dtStartDate && sod.SO.Date <= dtEndtDate)
                    {
                        FilteredSaleOrderDetails.Add(sod);
                    }
                }

                //if (FilteredSaleOrderDetails.Count > 0)
                //{
                    //prod.SODs = FilteredSaleOrderDetails;
                    

                //}
                


                /////////////////////////////

                FilteredPurchaseOrderDetails = new List<POD>();

                foreach (POD pod in prod.PODs)
                {
                    if (pod.PO.Date >= dtStartDate && pod.PO.Date <= dtEndtDate)
                    {
                        FilteredPurchaseOrderDetails.Add(pod);
                    }
                }

                //if (FilteredPurchaseOrderDetails.Count > 0)
                //{
                    //prod.PODs = FilteredPurchaseOrderDetails;
                    

                //}
                


                if (FilteredSaleOrderDetails.Count > 0 || FilteredPurchaseOrderDetails.Count > 0)
                {
                    prod.SODs = FilteredSaleOrderDetails;
                    prod.PODs = FilteredPurchaseOrderDetails;
                    FilteredProducts.Add(prod);

                }



            }

            dbVM.Products = FilteredProducts.OrderBy(x => x.Name).AsQueryable();



            ////////////////////////
           

            //dbVM.SOes = sOes;
            //dbVM.POes = db.POes;
            
            return View("Summary", dbVM);
            //return View("Dashboard", sOes);

        }
        public ActionResult FilterIndex(string custId, string suppId, string startDate, string endDate)
        {

            DateTime dtStartDate;
            DateTime dtEndtDate;

            if (startDate == string.Empty)
            {
                dtStartDate = DateTime.Parse("1-1-1800");
            }
            else
            {
                dtStartDate = DateTime.Parse(startDate);
            }

            if (endDate == string.Empty)
            {
                dtEndtDate = DateTime.Today.AddDays(1);
            }
            else
            {
                dtEndtDate = DateTime.Parse(endDate);
                dtEndtDate = dtEndtDate.AddDays(1);
            }

            ViewBag.Customers = DAL.dbCustomers;

            ViewBag.StartDate = dtStartDate.ToString("dd-MMM-yyyy");
            ViewBag.EndDate = dtEndtDate.ToString("dd-MMM-yyyy");

            DashboardViewModel dbVM = new DashboardViewModel();
          
          
          
            List<SOD> FilteredSaleOrderDetails;// = db.Customers;
            List<POD> FilteredPurchaseOrderDetails;// = db.Customers;
            List<Product> FilteredProducts = new List<Product>();
            foreach (Product prod in db.Products)
            {

                FilteredSaleOrderDetails = new List<SOD>();

                foreach (SOD sod in prod.SODs)
                {
                    if (sod.SO.Date >= dtStartDate && sod.SO.Date <= dtEndtDate)
                    {
                        FilteredSaleOrderDetails.Add(sod);
                    }
                }

                //if (FilteredSaleOrderDetails.Count > 0)
                //{
                    //prod.SODs = FilteredSaleOrderDetails;


                //}
                


                /////////////////////////////

                FilteredPurchaseOrderDetails = new List<POD>();

                foreach (POD pod in prod.PODs)
                {
                    if (pod.PO.Date >= dtStartDate && pod.PO.Date <= dtEndtDate)
                    {
                        FilteredPurchaseOrderDetails.Add(pod);
                    }
                }

                //if (FilteredPurchaseOrderDetails.Count > 0)
                //{
                    //prod.PODs = FilteredPurchaseOrderDetails;


                //}
               



                if (FilteredSaleOrderDetails.Count > 0 || FilteredPurchaseOrderDetails.Count > 0)
                {
                    prod.SODs = FilteredSaleOrderDetails;
                    prod.PODs = FilteredPurchaseOrderDetails;
                    FilteredProducts.Add(prod);

                }



            }

            dbVM.Products = FilteredProducts.OrderBy(x => x.Name).AsQueryable();





            return PartialView("_Summary", dbVM);
            //return View("Some thing went wrong");
        }
       
      
    }
}

MYBUSINESS/Views/StockTransections/Summary.cshtml
@*@model IEnumerable<MYBUSINESS.Models.SO>*@
@model MYBUSINESS.Models.DashboardViewModel
@{
    /**/

    ViewBag.Title = "Stock Transections Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* for modal *@

@*<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@

@*<link href="@Url.Content("~/Content/custom/custom.css")" rel="stylesheet" type="text/css" />*@
<script src="~/Content/custom/customerSOSR.js"></script>
@*<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>*@

<link href="@Url.Content("~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
@*<link href="@Url.Content("~/Content/custom/downloads/jquery-ui.min.css")" rel="stylesheet" type="text/css" />*@
<script src="~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>

@* ////////////////LAST GOOD///////////// *@
<link href="~/Content/custom/downloads/datatables.min.css" rel="stylesheet" />
<script src="~/Content/custom/downloads/datatables.min.js"></script>
<script src="~/Content/custom/downloads/jquery.mcautocomplete.js"></script>
@* ////////////LTE//////////////// *@
<!-- DataTables -->
@*<link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">*@

@* //picked from footer/// *@

<!-- DataTables -->
@*<script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>*@
@*<script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>*@

<center><h2>Stock Transections Summary</h2></center>


<input type="hidden" name="supplierId" id="supplierId" value="@ViewBag.SupplierId" />
@*<h1>@ViewBag.myLog</h1>*@



@*<p>
        @Html.ActionLink("Create New Sale Order", "Create")
    </p>*@

<form name="registration_form_Product" id='registration_form_Product' class="form-inline noPrint">
    <center>
        <div class="row">
            <input type="hidden" name="SaleOrder.CustomerId" id="idnCustomer" value="@ViewBag.CustomerId" />
            @*@Html.Label("Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @*@Html.Editor("custName", new { htmlAttributes = new { @class = "form-control", @placeholder = "Search by customer" } })*@

            @*<input type="text" autocomplete="off" class="form-control" name="Customer.Name" id="customer" value="" placeholder="Search by customer" data-toggle="tooltip" data-placement="top" title="Search by customer">*@
            <input type="hidden" autocomplete="off" class="form-control" name="Customer.Name" id="customer" value="" placeholder="Search by customer" data-toggle="tooltip" data-placement="top" title="Search by customer">

            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("startDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerStart", @placeholder = "Start date", @Value = ViewBag.StartDate } })


            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("endDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerEnd", @placeholder = "End date", @Value = ViewBag.EndDate } })

            <input type="button" value="Go" id="btnSearch" class="btn btn-warning add-new" />

            @*<input type="date" value="Search" id="btnSearch1" class="form-control " />*@

        </div>
    </center>
    @*<button class="printMe" value="print">Print</button>*@
    @*<a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>*@

    @*<div style='float:right;'>
            <button value="falsfja" style='position:fixed;'>heloo</button>
        </div>*@
    <div class="row">
        @*<div class="col-sm-8"><h2>Sale <b>Order</b></h2></div>*@

        <div class="col-sm-11">
            @*<textarea name="SaleOrder.Remarks" rows="1" cols="100" class="form-control" placeholder="Remarks..." data-toggle="tooltip" data-placement="top" title="Text of this text box will also print on bill"></textarea>*@
        </div>

        <div class="col-sm-1">
            @*<button type="submit" id="CreateSO" class="btn btn-info add-new"><i class="fa fa-plus"></i>Save & Print</button>*@
            <a href="#" id="printMe" class="btn btn-info "><i class=""></i> Print</a>
        </div>

    </div>

    @*<input type="button" onclick="printDiv('print-content')" value="print a div!" />*@
    @*<button onclick="myFunction()">Print this page</button>*@

</form>



@{Html.RenderPartial("_Summary", Model); }

@*<style type="text/css" media="print">
        .NonPrintable {
            display: none;
        }
        .Printable {
            display: block;
        }

    </style>*@

<style type="text/css" media="screen">
    .noPrint {
    }

    .noScreen {
        display: none;
    }
</style>

<style type="text/css" media="print">
    .noPrint {
        display: none;
    }

    .noScreen {
    }
</style>


<script type="text/javascript">
     @foreach (var d in ViewBag.Customers)
    {
        @*@:products.push(["@d.Name","@d.SalePrice","@d.Stock"]);*@
        @:customers.push(["@d.Id","@d.Name", "@d.Address", "@d.Balance"]);
    }
    //alert('abc');
    OnTypeCustomerName('#customer');

    $(function () { // will trigger when the document is ready
        //var date = $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' }).val();
        $('.datepicker').datepicker({
            dateFormat: 'dd-M-yy',
            showOn: "both"//,
            //buttonImageOnly: true,
            //buttonImage: "http://jqueryui.com/resources/demos/datepicker/images/calendar.gif",

            //buttonText: "Select date"
        });

    });

    $(document).ready(function () {
        //function myFunction() {
        //    window.print();
        //}
        //$("#printMe").show();
        //alert("abc");
        $('#printMe').click(function () {


            if ($.fn.DataTable.isDataTable('#PWS')) {
                $('#PWS').DataTable().destroy();
            }
            if ($.fn.DataTable.isDataTable('#CWS')) {
                $('#CWS').DataTable().destroy();
            }

            //$("#printMe").hide();

            window.print();

        });


        $('tr td.CustomerNameForSearch').click(function () {
            //alert($(this).text());
            //$('#idnCustomer').val();
            $('#customer').val($(this).text().trim());
            $('#idnCustomer').val($(this).closest("tr").find(".CustomerIdForSearch").text());
            SearchThis();
        });

        $('#btnSearch').click(function () {
            SearchThis();
        });

        function SearchThis() {
            //alert($('#idnCustomer').val());
            var custId = $('#idnCustomer').val();
            var suppId = $('#supplierId').val();
            if ($('#customer').val().trim() != "" && $('#idnCustomer').val() == "") {
                alert('Customer not found. Please select customer from list');
                return false;

            }


            //var startDate = $('#startDate').val();
            //var endDate = $('#endDate').val();

            var startDate = $('#datepickerStart').datepicker({ dateFormat: 'dd-mm-yy' }).val();
            var endDate = $('#datepickerEnd').datepicker({ dateFormat: 'dd-mm-yy' }).val();

            //if (startDate.trim() == "" && Date.parse(startDate)) {
            //    //Valid date
            //} else {
            //    alert("Start date is not valid");
            //    return false;
            //}

            //if (Date.parse(startDate)) {
            //    //Valid date
            //} else {
            //    alert("End date is not valid");
            //    return false;
            //}

            //$('#loading-image').show();
            $.ajax({
                url: "@Url.Action("FilterIndex", "StockTransections")",
                data: { 'custId': custId, 'suppId': suppId, 'startDate': startDate, 'endDate': endDate },
                type: "GET",
                cache: false,
                success: function (data) {
                    //alert(data);
                    $("#NewData").html(data);

                    //$("#hdnOrigComments").val($('#txtComments').val());
                    //$('#lblCommentsNotification').text(savingStatus);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
                    alert('Data provided was not valid');
                }
            });
        }

        //$('#btnSearch').click(function () {


        //});

    });


</script>

MYBUSINESS/Views/StockTransections/_Summary.cshtml
@*@model IEnumerable<MYBUSINESS.Models.SO>*@
@model MYBUSINESS.Models.DashboardViewModel


@{
    var carton = 0; //= (d.Stock / d.PerPack);
    var piece = 0;

    <div id="NewData">
        <div class="noScreen">
            <center><h4>@ViewBag.StartDate - @ViewBag.EndDate</h4></center>
        </div>
        <hr />

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        @*<div class="box-header">
                            <center><h3 class="box-title">Products</h3></center>
                        </div>*@
                        <div class="box-body">
                            <table class="table table-hover cell-border" id="PWS">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Product</th>
                                        <th>Opening stock</th>
                                        <th>Purchased stock</th>
                                        <th>Total</th>
                                        <th>Sold stock</th>
                                        <th>Balance</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @{

                                        int OpeningStock = 0;
                                        int ClosingStock = 0;
                                        int PurchasedStock = 0;
                                        int TotalStock = 0;
                                        int SoldStock = 0;
                                        int Balnace = 0;

                                        foreach (var product in Model.Products)
                                        {

                                            if (product.SODs.Count > 0)
                                            {
                                                OpeningStock = (int)(product.SODs.First().OpeningStock);
                                                ClosingStock = (int)(product.SODs.Last().OpeningStock);

                                            }
                                            if (product.PODs.Count > 0)
                                            {
                                                OpeningStock = (int)(product.PODs.First().OpeningStock);
                                                ClosingStock = (int)(product.PODs.Last().OpeningStock);

                                            }


                                            PurchasedStock = 0;
                                            foreach (var pod in product.PODs)
                                            {
                                                if (pod.SaleType == false)//purchase order
                                                {
                                                    if (pod.IsPack == true)
                                                    { PurchasedStock += (int)(pod.Quantity * pod.PerPack); }
                                                    else
                                                    { PurchasedStock += (int)(pod.Quantity); }

                                                }
                                                else
                                                {
                                                    if (pod.IsPack == true)
                                                    { PurchasedStock -= (int)(pod.Quantity * pod.PerPack); }
                                                    else
                                                    { PurchasedStock -= (int)(pod.Quantity); }
                                                }
                                            }
                                            SoldStock = 0;
                                            foreach (var sod in product.SODs)
                                            {
                                                if (sod.SaleType == false)//sale order
                                                {

                                                    if (sod.IsPack == true)
                                                    { SoldStock += (int)(sod.Quantity * sod.PerPack); }
                                                    else
                                                    { SoldStock += (int)(sod.Quantity); }


                                                }
                                                else
                                                {

                                                    if (sod.IsPack == true)
                                                    { SoldStock -= (int)(sod.Quantity * sod.PerPack); }
                                                    else
                                                    { SoldStock -= (int)(sod.Quantity); }

                                                }
                                            }

                                            <tr>
                                                <td>
                                                    @product.Id
                                                </td>
                                                <td>
                                                    @product.Name
                                                </td>
                                                <td>

                                                    @*@(OpeningStock / product.PerPack), @(OpeningStock % product.PerPack)*@

                                                    @{
                                                        carton = (int)(OpeningStock / product.PerPack);
                                                        piece = (int)(OpeningStock % product.PerPack);
                                                        if (piece == 0){@(carton)}else{@(carton.ToString() + ", " + piece.ToString())}
                                                    }
                                                </td>
                                                <td>
                                                    @*@(PurchasedStock / product.PerPack), @(PurchasedStock % product.PerPack)*@
                                                    @{
                                                        carton = (int)(PurchasedStock / product.PerPack);
                                                        piece = (int)(PurchasedStock % product.PerPack);
                                                        if (piece == 0){@(carton)}else{@(carton.ToString() + ", " + piece.ToString())}
                                                    }
                                                </td>

                                                <td>
                                                    @* return waly *@
                                                    @{TotalStock = OpeningStock + PurchasedStock;}
                                                    @*@(TotalStock / product.PerPack), @(TotalStock % product.PerPack)*@
                                                    @{
                                                        carton = (int)(TotalStock / product.PerPack);
                                                        piece = (int)(TotalStock % product.PerPack);
                                                        if (piece == 0){@(carton)}else{@(carton.ToString() + ", " + piece.ToString())}
                                                    }
                                                </td>
                                                <td>
                                                    @*@(SoldStock / product.PerPack), @(SoldStock % product.PerPack)*@
                                                    @{
                                                        carton = (int)(SoldStock / product.PerPack);
                                                        piece = (int)(SoldStock % product.PerPack);
                                                        if (piece == 0){@(carton)}else{@(carton.ToString() + ", " + piece.ToString())}
                                                    }
                                                </td>
                                                <td>
                                                    @{Balnace = TotalStock - SoldStock;}
                                                    @*@(Balnace / product.PerPack), @(Balnace % product.PerPack)*@
                                                    @{
                                                        carton = (int)(Balnace / product.PerPack);
                                                        piece = (int)(Balnace % product.PerPack);
                                                        if (piece == 0){@(carton)}else{@(carton.ToString() + ", " + piece.ToString())}
                                                    }

                                                </td>

                                            </tr>
                                            //}

                                        }
                                    }
                                </tbody>
                                <tfoot>
                                    @*<tr style="font-weight:bold">
                                            <td>Total</td>
                                            <td>@totSOQty</td>
                                            <td>@totSOAmnt.ToString("0.00")</td>
                                            <td>@totSRQty</td>
                                            <td>@totSRAmnt.ToString("0.00")</td>
                                            <td>@totProfit.ToString("0.00")</td>
                                        </tr>*@
                                </tfoot>
                            </table>
                        </div>
                    </div>

                    @* other table *@


                </div>
            </div>
            *E.g. 10, 2 = 10 packs, 2 pieces
        </section>




        @* ////////////////////////////////////////////////////////////////////////////////////////////////// *@

    </div>

}

<script type="text/javascript">
    $(document).ready(function () {



        $('#PWS').DataTable({
            //fixedHeader: {
            //    header: true,
            //    footer: true
            //},
            //"sScrollX": "100%",
            //"scrollX": true,
            "scrollY": "400px",
            "scrollCollapse": true,
            "paging": false,
            "bInfo": false,
            "order": [[0, "asc"]],
            "searching": false
        });




    });


</script>