MYBUSINESS/Models/Expense.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expense()
        {
            this.ExpenseDetails = new HashSet<ExpenseDetail>();
        }
    
        public string Id { get; set; }
        public Nullable<decimal> POSerial { get; set; }
        public decimal BillAmount { get; set; }
        public decimal BillPaid { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> PrevBalance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> PurchaseReturn { get; set; }
        public Nullable<decimal> SupplierId { get; set; }
        public Nullable<decimal> PurchaseOrderAmount { get; set; }
        public Nullable<decimal> PurchaseOrderQty { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentDetail { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<decimal> EmployeeId { get; set; }
        public Nullable<decimal> FundingSourceId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseDetail> ExpenseDetails { get; set; }
    }
}

MYBUSINESS/Models/ExpenseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MYBUSINESS.Models
{
    public class ExpenseViewModel
    {
        public IQueryable<Supplier> Suppliers { get; set; }
        public Supplier Supplier { get; set; }
        public Expense PurchaseOrder { get; set; }
        public List<ExpenseDetail> PurchaseOrderDetail { get; set; }
        public IQueryable<Product> Products { get; set; }
        public Product Product { get; set; }
        //public List<FundingSource> FundingSources { get; set; }

    }
}

MYBUSINESS/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Drawing.Printing;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

using Microsoft.Reporting.WebForms;
using MYBUSINESS.CustomClasses;
using MYBUSINESS.Models;

namespace MYBUSINESS.Controllers
{
    public class ExpenseController : Controller
    {
        private BusinessContext db = new BusinessContext();

        // GET: POes
        public ActionResult Index()
        {
            DateTime PKDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Pakistan Standard Time"));
            var dtStartDate = new DateTime(PKDate.Year, PKDate.Month, 1);
            var dtEndtDate = dtStartDate.AddMonths(1).AddSeconds(-1);

            //IQueryable<Expense> pOes = db.POes.Include(s => s.Supplier);
            IQueryable<Expense> pOes = db.Expenses.Where(x => x.Date >= dtStartDate && x.Date <= dtEndtDate).Include(s => s.Supplier);
            //pOes.ForEachAsync(m => m.Id = Encryption.Encrypt(m.Id, "BZNS"));
            //var pOes = db.POes.Where(s => s.SaleReturn == false);
            GetTotalBalance(ref pOes);
            Dictionary<decimal, decimal> LstMaxSerialNo = new Dictionary<decimal, decimal>();
            int thisSerial = 0;
            foreach (Expense itm in pOes)
            {
                thisSerial = (int)itm.Supplier.Expenses.Max(x => x.POSerial);

                if (!LstMaxSerialNo.ContainsKey((int)itm.SupplierId))
                {
                    LstMaxSerialNo.Add(itm.Supplier.Id, thisSerial);
                }

                //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
                itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            }
            ViewBag.LstMaxSerialno = LstMaxSerialNo;
            ViewBag.Suppliers = db.Suppliers;
            ViewBag.StartDate = dtStartDate.ToString("dd-MMM-yyyy");
            ViewBag.EndDate = dtEndtDate.ToString("dd-MMM-yyyy");
            return View(pOes.OrderByDescending(i => i.Date).ToList());
        }
        //public ActionResult SearchData(string custName, DateTime startDate, DateTime endDate)

        //public ActionResult SearchData(string custName, string startDate, string endDate)
        public ActionResult SearchData(string suppId, string startDate, string endDate)
        {

            int intSuppId;
            DateTime dtStartDate;
            DateTime dtEndtDate;
            IQueryable<Expense> selectedPOes = null;
            if (endDate != string.Empty)
            {
                dtEndtDate = DateTime.Parse(endDate);
                dtEndtDate = dtEndtDate.AddDays(1);
                endDate = dtEndtDate.ToString();

            }

            if (suppId != string.Empty && startDate != string.Empty && endDate != string.Empty)
            {
                intSuppId = Int32.Parse(suppId);
                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Parse(endDate);

                selectedPOes = db.Expenses.Where(so => so.SupplierId == intSuppId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            if (suppId == string.Empty && startDate == string.Empty && endDate == string.Empty)
            {

                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedPOes = db.Expenses;//.Where(so => so.SupplierId == intSuppId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get all customers data acornding to start end date
            if (suppId == string.Empty && startDate != string.Empty && endDate != string.Empty)
            {

                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Parse(endDate);

                selectedPOes = db.Expenses.Where(so => so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get this customer with from undefined startdate to this defined enddate
            if (suppId != string.Empty && startDate == string.Empty && endDate != string.Empty)
            {
                intSuppId = Int32.Parse(suppId.Trim());
                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Parse(endDate);

                selectedPOes = db.Expenses.Where(so => so.SupplierId == intSuppId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get this customer with from defined start date to undefined end date
            if (suppId != string.Empty && startDate != string.Empty && endDate == string.Empty)
            {
                intSuppId = Int32.Parse(suppId.Trim());
                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedPOes = db.Expenses.Where(so => so.SupplierId == intSuppId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get this customer with all dates
            if (suppId != string.Empty && startDate == string.Empty && endDate == string.Empty)
            {
                intSuppId = Int32.Parse(suppId.Trim());
                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedPOes = db.Expenses.Where(so => so.SupplierId == intSuppId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get all customer with defined startdate and undefined end date
            if (suppId == string.Empty && startDate != string.Empty && endDate == string.Empty)
            {

                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedPOes = db.Expenses.Where(so => so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get all customers with undifined start date with defined enddate
            if (suppId == string.Empty && startDate == string.Empty && endDate != string.Empty)
            {

                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Parse(endDate);

                selectedPOes = db.Expenses.Where(so => so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            GetTotalBalance(ref selectedPOes);
            Dictionary<decimal, decimal> LstMaxSerialNo = new Dictionary<decimal, decimal>();
            int thisSerial = 0;
            foreach (Expense itm in selectedPOes)
            {
                thisSerial = (int)itm.Supplier.Expenses.Max(x => x.POSerial);
                if (!LstMaxSerialNo.ContainsKey((int)itm.SupplierId))
                {
                    LstMaxSerialNo.Add(itm.Supplier.Id, thisSerial);
                }
                //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
                itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            }

            return PartialView("_SelectedPOPR", selectedPOes.OrderByDescending(i => i.Date).ToList());

            //return View("Some thing went wrong");


        }
        public ActionResult PerMonthPurchase(int productId)
        {
            IQueryable<Expense> pOes = db.Expenses.Include(s => s.Supplier);

            //sOes = db.SOes.Where(x => x.SODs.Where(y => y.ProductId == productId));

            List<ExpenseDetail> lstPODs = db.ExpenseDetails.Where(x => x.ProductId == productId && x.SaleType == false).ToList();
            List<Expense> lstSlectedPO = new List<Expense>();
            foreach (ExpenseDetail lpod in lstPODs)
            {
                if (lstSlectedPO.Where(x => x.Id == lpod.POId).FirstOrDefault() == null)
                {
                    lstSlectedPO.Add(lpod.Expense);
                }
            }

            pOes = lstSlectedPO.ToList().AsQueryable();
            foreach (Expense itm in pOes)
            {
                //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
                itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            }
            ViewBag.ProductName = db.Products.FirstOrDefault(x => x.Id == productId).Name;
            return View("PerMonthPurchase", pOes.OrderBy(i => i.Date).ToList());
        }

        public ActionResult SearchProduct(int productId)
        {
            IQueryable<Expense> pOes = db.Expenses.Include(s => s.Supplier);

            List<ExpenseDetail> lstPODs = db.ExpenseDetails.Where(x => x.ProductId == productId).ToList();
            List<Expense> lstSlectedPO = new List<Expense>();
            foreach (ExpenseDetail lpod in lstPODs)
            {
                if (lstSlectedPO.Where(x => x.Id == lpod.POId).FirstOrDefault() == null)
                {
                    lstSlectedPO.Add(lpod.Expense);
                }


            }

            pOes = lstSlectedPO.ToList().AsQueryable();

            //sOes.ForEachAsync(m => m.Id = Encryption.Encrypt(m.Id, "BZNS"));
            //var sOes = db.SOes.Where(s => s.SaleReturn == false);
            GetTotalBalance(ref pOes);
            foreach (Expense itm in pOes)
            {

                //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
                itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            }
            ViewBag.Suppliers = db.Suppliers;
            return View("Index", pOes.OrderByDescending(i => i.Date).ToList());
        }

        private void GetTotalBalance(ref IQueryable<Expense> POes)
        {
            //IQueryable<SO> DistSOes = SOes.Select(x => x.CustomerId).Distinct();
            IQueryable<Expense> DistPOes = POes.GroupBy(x => x.SupplierId).Select(y => y.FirstOrDefault());

            decimal TotalBalance = 0;
            foreach (Expense itm in DistPOes)
            {

MYBUSINESS/Views/Expense/Delete.cshtml
@model MYBUSINESS.Models.SO

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SODId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SODId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SOSerial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SOSerial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SaleReturn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleReturn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MYBUSINESS/Views/Expense/Details.cshtml
@model MYBUSINESS.Models.SO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SO</h4>
    <hr />
    <dl class="dl-horizontal">
        

        <dt>
            @Html.DisplayNameFor(model => model.BillAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SaleReturn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleReturn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SODId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SODId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MYBUSINESS/Views/Expense/Index.cshtml
@model IEnumerable<MYBUSINESS.Models.Expense>

@{
    ViewBag.Title = "Business Expense";
    //Layout = "~/Views/Shared/_Layout.cshtml";

}

@* for modal *@


<link href="@Url.Content("~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
@*<link href="@Url.Content("~/Content/custom/downloads/jquery-ui.min.css")" rel="stylesheet" type="text/css" />*@
<script src="~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>


@*<link href="@Url.Content("~/Content/custom/custom.css")" rel="stylesheet" type="text/css" />*@
<script src="~/Content/custom/supplierPOPR.js"></script>

<link href="~/Content/custom/downloads/datatables.min.css" rel="stylesheet" />
<script src="~/Content/custom/downloads/datatables.min.js"></script>
<script src="~/Content/custom/downloads/jquery.mcautocomplete.js"></script>
<center><h2>Expenses</h2></center>

@*<h1>@ViewBag.myLog</h1>*@



@*<p>
        @Html.ActionLink("Create New Purchase Order", "Create")
    </p>*@
<div class="col-sm-1">
    @*<button type="submit" id="CreatePO" class="btn btn-info add-new"><i class="fa fa-plus"></i>Save & Print</button>*@
    <a href="/Expense/Create?IsReturn=false" id="createPOPR" class="btn btn-info "><i class=""></i> New Expense</a>
</div>
<form name="registration_form_Product" id='registration_form_Product' class="form-inline">
    <center>
        <div class="row">
            <input type="hidden" name="PurchaseOrder.SupplierId" id="idnSupplier" value="" />
            @*@Html.Label("Supplier Name", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @*@Html.Editor("suppName", new { htmlAttributes = new { @class = "form-control", @placeholder = "Search by supplier" } })*@
            <input type="text" autocomplete="off" class="form-control" name="SupplierName" id="supplier" value="" placeholder="Search by supplier" data-toggle="tooltip" data-placement="top" title="Search by supplier">

            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("startDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerStart", @placeholder = "Start date", @Value = ViewBag.StartDate } })


            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("endDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerEnd", @placeholder = "End date", @Value = ViewBag.EndDate } })

            <input type="button" value="Go" id="btnSearch" class="btn btn-warning add-new" />

            @*<input type="date" value="Search" id="btnSearch1" class="form-control " />*@

        </div>
    </center>
</form>

@{Html.RenderPartial("_SelectedPOPR", Model); }


<script type="text/javascript">
        @foreach(var d in ViewBag.Suppliers)
        {
            @*@: products.push(["@d.Name", "@d.PurchasePrice", "@d.Stock"]);*@
            @: suppliers.push(["@d.Id", "@d.Name", "@d.Address", "@d.Balance"]);
        }

        OnTypeSupplierName('#supplier');
        $(function () { // will trigger when the document is ready
            //var date = $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' }).val();
            $('.datepicker').datepicker({
                dateFormat: 'dd-M-yy',
                showOn: "both"//,
                //buttonImageOnly: true,
                //buttonImage: "http://jqueryui.com/resources/demos/datepicker/images/calendar.gif",

                //buttonText: "Select date"
            });

        });

        $(document).ready(function () {

            $('tr td.SupplierNameForSearch').click(function () {
                //alert($(this).text());
                //$('#idnSupplier').val();
                $('#supplier').val($(this).text().trim());
                $('#idnSupplier').val($(this).closest("tr").find(".SupplierIdForSearch").text());
                SearchThis();
            });

            $('#btnSearch').click(function () {
                SearchThis();
            });

            function SearchThis() {
                //alert("yes");
                var suppId = $('#idnSupplier').val();

                if ($('#supplier').val().trim() != "" && $('#idnSupplier').val() == "") {
                    alert('Supplier not found. Please select supplier from list');
                    return false;

                }


                //var startDate = $('#startDate').val();
                //var endDate = $('#endDate').val();

                var startDate = $('#datepickerStart').datepicker({ dateFormat: 'dd-mm-yy' }).val();
                var endDate = $('#datepickerEnd').datepicker({ dateFormat: 'dd-mm-yy' }).val();

                //if (startDate.trim() == "" && Date.parse(startDate)) {
                //    //Valid date
                //} else {
                //    alert("Start date is not valid");
                //    return false;
                //}

                //if (Date.parse(startDate)) {
                //    //Valid date
                //} else {
                //    alert("End date is not valid");
                //    return false;
                //}

                //$('#loading-image').show();
                $.ajax({
                    url: "@Url.Action("SearchData","Expense")",
                    data: { 'suppId': suppId, 'startDate': startDate, 'endDate': endDate },
                    type: "GET",
                    cache: false,
                    success: function (data) {
                        //alert(data);
                        $("#NewData").html(data);

                        //$("#hdnOrigComments").val($('#txtComments').val());
                        //$('#lblCommentsNotification').text(savingStatus);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
                        alert('Data provided was not valid');
                    }
                });
            }

            //$('#btnSearch').click(function () {


            //});


        });


</script>

MYBUSINESS/Views/Expense/PerMonthPurchase.cshtml
@model IEnumerable<MYBUSINESS.Models.Expense>
<center><h2>Per Month Purchase</h2></center>
<center><h4> @ViewBag.ProductName</h4></center>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Month")
        </th>
        <th style="display:none;">
            @Html.DisplayNameFor(model => model.Id)
        </th>

        <th>
            @*@Html.DisplayName("Order No.")*@
            Order No.
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Supplier.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PODs.First().Quantity)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.SODs.First().PurchasePrice)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.SODs.First().SalePrice)
            </th>*@
        @*<th>
                @Html.DisplayName("Profit")
            </th>*@

    </tr>
    @{
        string month = string.Empty;
        //decimal totProfit = 0;
        //decimal monthlyProfit = 0;
        //decimal profit = 0;
        int totQty = 0;
        int monthlyQty = 0;
        decimal salePrice = 0;
        foreach (var item in Model)
        {
            if (month == string.Empty)
            {
                month = item.Date.Value.Month.ToString();
            }
            else
            {
                if (month != item.Date.Value.Month.ToString())
                {
                    month = item.Date.Value.Month.ToString();
                    <tr style="font-weight:bold">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>@(monthlyQty)</td>
                        @*<td>@(monthlyProfit)</td>*@
                    </tr>
                    //monthlyProfit = 0;
                    monthlyQty = 0;
                }
            }


            foreach (var subItem in item.PODs)
            {

                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td style="display:none;">
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.POSerial)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Supplier.Name)
                    </td>

                    <td>
                        @*@Html.DisplayFor(modelSubItem => subItem.Quantity)*@
                        @{

                            monthlyQty += (int)subItem.Quantity;
                            totQty += (int)subItem.Quantity;
                        }
                        @(subItem.Quantity)
                    </td>
                    @*<td>
                            @(subItem.PurchasePrice * subItem.Quantity)
                        </td>*@
                    @*<td>
                            @(subItem.SalePrice * subItem.Quantity)
                        </td>*@

                    @*<td>
                            @{
                                profit = (decimal)(subItem.PurchasePrice * subItem.Quantity) - (decimal)(subItem.PurchasePrice * subItem.Quantity);
                                monthlyProfit += profit;
                                totProfit += profit;

                            }
                            @(profit)
                        </td>*@
                </tr>
            }

        }
        <tr style="font-weight:bold">
            <td></td>
            <td></td>
            <td></td>
            <td>@(monthlyQty)</td>
            @*<td>@(monthlyProfit)</td>*@
        </tr>
        <tr style="font-weight:bold">
            <td></td>
            <td></td>
            <td>Total</td>
            <td>@(totQty)</td>
            @*<td>@(totProfit)</td>*@
        </tr>
    }
</table>