MYBUSINESS/Models/ProductDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public decimal Id { get; set; }
        public string RentId { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Rent Rent { get; set; }
    }
}

MYBUSINESS/Controllers/SOSRController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Drawing.Printing;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

using Microsoft.Reporting.WebForms;
using MYBUSINESS.CustomClasses;
using MYBUSINESS.Models;

namespace MYBUSINESS.Controllers
{

    //[OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    //[NoCache]
    public class SOSRController : Controller
    {
        private BusinessContext db = new BusinessContext();
        private DAL DAL = new DAL();
        // GET: SOes
        public ActionResult Index()
        {
            //EnterProfit();
            DateTime PKDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Pakistan Standard Time"));
            var dtStartDate = new DateTime(PKDate.Year, PKDate.Month, 1);
            var dtEndtDate = dtStartDate.AddMonths(1).AddSeconds(-1);

            IQueryable<SO> sOes = db.SOes.Where(x => x.Date >= dtStartDate && x.Date <= dtEndtDate).Include(s => s.Customer);
            //sOes = sOes.Where(x => x.Date >= dtStartDate && x.Date <= dtEndtDate);
            //sOes.ForEachAsync(m => m.Id = Encryption.Encrypt(m.Id, "BZNS"));
            //var sOes = db.SOes.Where(s => s.SaleReturn == false);
            GetTotalBalance(ref sOes);
            Dictionary<decimal, decimal> LstMaxSerialNo = new Dictionary<decimal, decimal>();
            int thisSerial = 0;
            foreach (SO itm in sOes)
            {
                thisSerial = (int)itm.Customer.SOes.Max(x => x.SOSerial);

                if (!LstMaxSerialNo.ContainsKey((int)itm.CustomerId))
                {
                    LstMaxSerialNo.Add(itm.Customer.Id, thisSerial);
                }


                //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
                itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            }

            ViewBag.LstMaxSerialno = LstMaxSerialNo;
            ViewBag.Customers = DAL.dbCustomers;
            ViewBag.StartDate = dtStartDate.ToString("dd-MMM-yyyy");
            ViewBag.EndDate = dtEndtDate.ToString("dd-MMM-yyyy");
            return View(sOes.OrderByDescending(i => i.Date).ToList());
        }
        public ActionResult ProductRentStatus(string prodId, string sellDate)
        {
            int intProdId;
            DateTime dtSellDate;
            DateTime dtEndDate;
            //IQueryable<ProductDetail> selectedSOes = null;
            List<ProductDetail> selectedSOes = null;
            //if (prodId != string.Empty && startDate != string.Empty && endDate != string.Empty)
            //{
            intProdId = Int32.Parse(prodId);
            //dtSellDate = DateTime.Parse(sellDate);
            //dtSellDate = DateTime.ParseExact(sellDate, "dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture);
            dtSellDate = DateTime.ParseExact(sellDate, "d/M/yyyy", CultureInfo.InvariantCulture);
            //dtEndDate = DateTime.Parse(endDate);

            selectedSOes = db.ProductDetails.Where(so => so.ProductId == intProdId && (so.RentStartDate >= dtSellDate || so.RentEndDate >= dtSellDate)).ToList();

            //return PartialView("_SelectedSOSR", selectedSOes.OrderByDescending(i => i.Date).ToList());
            return PartialView("_ProductDetail", selectedSOes);//.ToList());
            //return PartialView("1");
        }
        //public ActionResult SearchData(string custName, DateTime startDate, DateTime endDate)

        //public ActionResult SearchData(string custName, string startDate, string endDate)
        public ActionResult SearchData(string custId, string startDate, string endDate)
        {

            int intCustId;
            DateTime dtStartDate;
            DateTime dtEndtDate;
            IQueryable<SO> selectedSOes = null;
            if (endDate != string.Empty)
            {
                dtEndtDate = DateTime.Parse(endDate);
                dtEndtDate = dtEndtDate.AddDays(1);
                endDate = dtEndtDate.ToString();

            }

            if (custId != string.Empty && startDate != string.Empty && endDate != string.Empty)
            {
                intCustId = Int32.Parse(custId);
                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Parse(endDate);

                selectedSOes = db.SOes.Where(so => so.CustomerId == intCustId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            if (custId == string.Empty && startDate == string.Empty && endDate == string.Empty)
            {

                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedSOes = db.SOes;//.Where(so => so.CustomerId == intCustId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get all customers data acornding to start end date
            if (custId == string.Empty && startDate != string.Empty && endDate != string.Empty)
            {

                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Parse(endDate);

                selectedSOes = db.SOes.Where(so => so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get this customer with from undefined startdate to this defined enddate
            if (custId != string.Empty && startDate == string.Empty && endDate != string.Empty)
            {
                intCustId = Int32.Parse(custId);
                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Parse(endDate);

                selectedSOes = db.SOes.Where(so => so.CustomerId == intCustId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get this customer with from defined start date to undefined end date
            if (custId != string.Empty && startDate != string.Empty && endDate == string.Empty)
            {
                intCustId = Int32.Parse(custId);
                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedSOes = db.SOes.Where(so => so.CustomerId == intCustId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get this customer with all dates
            if (custId != string.Empty && startDate == string.Empty && endDate == string.Empty)
            {
                intCustId = Int32.Parse(custId);
                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedSOes = db.SOes.Where(so => so.CustomerId == intCustId && so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get all customer with defined startdate and undefined end date
            if (custId == string.Empty && startDate != string.Empty && endDate == string.Empty)
            {

                dtStartDate = DateTime.Parse(startDate);
                dtEndtDate = DateTime.Today.AddDays(1);

                selectedSOes = db.SOes.Where(so => so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }

            //get all customers with undifined start date with defined enddate
            if (custId == string.Empty && startDate == string.Empty && endDate != string.Empty)
            {

                dtStartDate = DateTime.Parse("1-1-1800");
                dtEndtDate = DateTime.Parse(endDate);

                selectedSOes = db.SOes.Where(so => so.Date >= dtStartDate && so.Date <= dtEndtDate);

            }
            GetTotalBalance(ref selectedSOes);
            Dictionary<decimal, decimal> LstMaxSerialNo = new Dictionary<decimal, decimal>();
            int thisSerial = 0;
            foreach (SO itm in selectedSOes)
            {
                thisSerial = (int)itm.Customer.SOes.Max(x => x.SOSerial);

                if (!LstMaxSerialNo.ContainsKey((int)itm.CustomerId))
                {
                    LstMaxSerialNo.Add(itm.Customer.Id, thisSerial);
                }
                //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
                itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            }
            ViewBag.LstMaxSerialno = LstMaxSerialNo;
            return PartialView("_SelectedSOSR", selectedSOes.OrderByDescending(i => i.Date).ToList());

            //return View("Some thing went wrong");


        }
        public ActionResult CustomerWiseSale(int custId, string custName)
        {

            //DateTime dtEndtDate = DateTime.Today.AddDays(1);
            //DateTime dtStartDate = dtEndtDate.AddDays(-7);
            DateTime PKDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Pakistan Standard Time"));
            var dtStartDate = new DateTime(PKDate.Year, PKDate.Month, 1);
            var dtEndtDate = dtStartDate.AddMonths(1).AddSeconds(-1);

            ViewBag.CustomerId = custId;
            ViewBag.CustName = custName;
            //ViewBag.SupplierName = supplierName;//db.Products.FirstOrDefault(x => x.Id == productId).Name;
            ViewBag.Customers = DAL.dbCustomers;
            //01-Jan-2019

            ViewBag.StartDate = dtStartDate.ToString("dd-MMM-yyyy");
            ViewBag.EndDate = dtEndtDate.ToString("dd-MMM-yyyy");

            IQueryable<SO> sOes = db.SOes;//.Include(s => s.Customer);
            sOes = sOes.Where(x => x.CustomerId == custId && x.Date >= dtStartDate && x.Date <= dtEndtDate).OrderBy(i => i.SOSerial).AsQueryable();
            //foreach (SO itm in sOes)
            //{
            //    //itm.Id = Encryption.Encrypt(itm.Id, "BZNS");
            //    itm.Id = string.Join("-", ASCIIEncoding.ASCII.GetBytes(Encryption.Encrypt(itm.Id, "BZNS")));
            //}

            return View("CustomerWiseSale", sOes);

MYBUSINESS/Views/SOSR/CustomerWiseSale.cshtml
@model IEnumerable<MYBUSINESS.Models.SO>

@{
    ViewBag.Title = "Customer Wise Sale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* for modal *@

<link href="@Url.Content("~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
@*<link href="@Url.Content("~/Content/custom/downloads/jquery-ui.min.css")" rel="stylesheet" type="text/css" />*@
<script src="~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>

@*<link href="@Url.Content("~/Content/custom/custom.css")" rel="stylesheet" type="text/css" />*@
<script src="~/Content/custom/customerSOSR.js"></script>
<script src="~/Content/custom/downloads/jquery.mcautocomplete.js"></script>
@*<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>*@
<link href="~/Content/custom/downloads/datatables.min.css" rel="stylesheet" />
<script src="~/Content/custom/downloads/datatables.min.js"></script>

<center><h2>Customer Wise Sale</h2></center>
<center><h4>@ViewBag.CustName</h4></center>
<input type="hidden" name="supplierId" id="supplierId" value="@ViewBag.SupplierId" />
@*<h1>@ViewBag.myLog</h1>*@



@*<p>
        @Html.ActionLink("Create New Sale Order", "Create")
    </p>*@

<form name="registration_form_Product" id='registration_form_Product' class="form-inline">
    <center>
        <div class="row">
            <input type="hidden" name="SaleOrder.CustomerId" id="idnCustomer" value="@ViewBag.CustomerId" />
            @*@Html.Label("Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @*@Html.Editor("custName", new { htmlAttributes = new { @class = "form-control", @placeholder = "Search by customer" } })*@

            @*<input type="text" autocomplete="off" class="form-control" name="Customer.Name" id="customer" value="" placeholder="Search by customer" data-toggle="tooltip" data-placement="top" title="Search by customer">*@
            <input type="hidden" autocomplete="off" class="form-control" name="Customer.Name" id="customer" value="" placeholder="Search by customer" data-toggle="tooltip" data-placement="top" title="Search by customer">

            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("startDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerStart", @placeholder = "Start date", @Value = ViewBag.StartDate } })


            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("endDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerEnd", @placeholder = "End date", @Value = ViewBag.EndDate } })

            <input type="button" value="Go" id="btnSearch" class="btn btn-warning add-new" />

            @*<input type="date" value="Search" id="btnSearch1" class="form-control " />*@

        </div>
    </center>
</form>

@{Html.RenderPartial("_CustomerWiseSale", Model); }


<script type="text/javascript">
     @foreach (var d in ViewBag.Customers)
    {
        @*@:products.push(["@d.Name","@d.SalePrice","@d.Stock"]);*@
        @:customers.push(["@d.Id","@d.Name", "@d.Address", "@d.Balance"]);
    }

    OnTypeCustomerName('#customer');
    $(function () { // will trigger when the document is ready
        //var date = $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' }).val();
        $('.datepicker').datepicker({
            dateFormat: 'dd-M-yy',
            showOn: "both"//,
            //buttonImageOnly: true,
            //buttonImage: "http://jqueryui.com/resources/demos/datepicker/images/calendar.gif",

            //buttonText: "Select date"
        });

    });

    $(document).ready(function () {
        $('tr td.CustomerNameForSearch').click(function () {
            //alert($(this).text());
            //$('#idnCustomer').val();
            $('#customer').val($(this).text().trim());
            $('#idnCustomer').val($(this).closest("tr").find(".CustomerIdForSearch").text());
            SearchThis();
        });

        $('#btnSearch').click(function () {
            SearchThis();
        });

        function SearchThis() {
            //alert($('#idnCustomer').val());
            var custId = $('#idnCustomer').val();
            var suppId = $('#supplierId').val();
            if ($('#customer').val().trim() != "" && $('#idnCustomer').val() == "") {
                alert('Customer not found. Please select customer from list');
                return false;

            }


            //var startDate = $('#startDate').val();
            //var endDate = $('#endDate').val();

            var startDate = $('#datepickerStart').datepicker({ dateFormat: 'dd-mm-yy' }).val();
            var endDate = $('#datepickerEnd').datepicker({ dateFormat: 'dd-mm-yy' }).val();

            //if (startDate.trim() == "" && Date.parse(startDate)) {
            //    //Valid date
            //} else {
            //    alert("Start date is not valid");
            //    return false;
            //}

            //if (Date.parse(startDate)) {
            //    //Valid date
            //} else {
            //    alert("End date is not valid");
            //    return false;
            //}

            //$('#loading-image').show();
            $.ajax({
                url: "@Url.Action("FilterCustomerWiseSale", "SOSR")",
                data: { 'custId': custId, 'suppId': suppId, 'startDate': startDate, 'endDate': endDate },
                type: "GET",
                cache: false,
                success: function (data) {
                    //alert(data);
                    $("#NewData").html(data);

                    //$("#hdnOrigComments").val($('#txtComments').val());
                    //$('#lblCommentsNotification').text(savingStatus);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
                    alert('Data provided was not valid');
                }
            });
        }

        //$('#btnSearch').click(function () {


        //});

    });


</script>

MYBUSINESS/Views/SOSR/Index.cshtml
@model IEnumerable<MYBUSINESS.Models.SO>

@{
    ViewBag.Title = "Sale Orders";
    //Layout = "~/Views/Shared/_Layout.cshtml";

}

@* for modal *@



<link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css" rel="stylesheet" />

@*<script src="https://code.jquery.com/jquery-3.5.1.js"></script>*@
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script>
@*<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.html5.min.js"></script>*@
<script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.print.min.js"></script>


<link href="https://cdn.datatables.net/rowreorder/1.2.8/css/rowReorder.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/rowreorder/1.2.8/js/dataTables.rowReorder.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>






<link href="@Url.Content("~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

<script src="~/Content/custom/downloads/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>



<script src="~/Content/custom/customerSOSR.js"></script>

<script src="~/Content/custom/downloads/jquery.mcautocomplete.js"></script>

<center><h2>Sales</h2></center>

@*<h1>@ViewBag.myLog</h1>*@



@*<p>
        @Html.ActionLink("Create New Sale Order", "Create")
    </p>*@
<div class="col-sm-1">
    @*<button type="submit" id="CreateSO" class="btn btn-info add-new"><i class="fa fa-plus"></i>Save & Print</button>*@
    <a href="/SOSR/Create?IsReturn=false" id="createSOSR" class="btn btn-success "><i class=""></i> New Sale</a>
</div>
<form name="registration_form_Product" id='registration_form_Product' class="form-inline">
    <center>
        <div class="row">
            <input type="hidden" name="SaleOrder.CustomerId" id="idnCustomer" value="" />
            @*@Html.Label("Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @*@Html.Editor("custName", new { htmlAttributes = new { @class = "form-control", @placeholder = "Search by customer" } })*@
            <input type="text" autocomplete="off" class="form-control" name="Customer.Name" id="customer" value="" placeholder="Search by customer" data-toggle="tooltip" data-placement="top" title="Search by customer">

            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("startDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerStart", @placeholder = "Start date", @Value = ViewBag.StartDate } })


            @*@Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })*@

            @Html.Editor("endDate", new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepickerEnd", @placeholder = "End date", @Value = ViewBag.EndDate } })

            <input type="button" value="Go" id="btnSearch" class="btn btn-warning add-new" />

            @*<input type="date" value="Search" id="btnSearch1" class="form-control " />*@

        </div>
    </center>
</form>

@{Html.RenderPartial("_SelectedSOSR", Model); }


<script type="text/javascript">
    @foreach (var d in ViewBag.Customers)
    {
        @*@:products.push(["@d.Name","@d.SalePrice","@d.Stock"]);*@
        @:customers.push(["@d.Id","@d.Name", "@d.Address", "@d.Balance"]);
    }

    OnTypeCustomerName('#customer');
    $(function () { // will trigger when the document is ready
        //var date = $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' }).val();
        $('.datepicker').datepicker({
            dateFormat: 'dd-M-yy',
            showOn: "both"//,
            //buttonImageOnly: true,
            //buttonImage: "http://jqueryui.com/resources/demos/datepicker/images/calendar.gif",

            //buttonText: "Select date"
        });

    });

    $(document).ready(function () {

        $('tr td.CustomerNameForSearch').click(function () {
            //alert($(this).text());
            //$('#idnCustomer').val();
            $('#customer').val($(this).text().trim());
            $('#idnCustomer').val($(this).closest("tr").find(".CustomerIdForSearch").text());
            SearchThis();
        });

        $('#btnSearch').click(function () {
            SearchThis();
        });

        function SearchThis() {
            //alert("yes");
            var custId = $('#idnCustomer').val();

            if ($('#customer').val().trim() != "" && $('#idnCustomer').val() == "") {
                alert('Customer not found. Please select customer from list');
                return false;

            }


            //var startDate = $('#startDate').val();
            //var endDate = $('#endDate').val();

            var startDate = $('#datepickerStart').datepicker({ dateFormat: 'dd-mm-yy' }).val();
            var endDate = $('#datepickerEnd').datepicker({ dateFormat: 'dd-mm-yy' }).val();

            //if (startDate.trim() == "" && Date.parse(startDate)) {
            //    //Valid date
            //} else {
            //    alert("Start date is not valid");
            //    return false;
            //}

            //if (Date.parse(startDate)) {
            //    //Valid date
            //} else {
            //    alert("End date is not valid");
            //    return false;
            //}

            //$('#loading-image').show();
            $.ajax({
                url: "@Url.Action("SearchData","SOSR")",
                data: { 'custId': custId, 'startDate': startDate, 'endDate': endDate },
                type: "GET",
                cache: false,
                success: function (data) {
                    //alert(data);
                    $("#NewData").html(data);

                    //$("#hdnOrigComments").val($('#txtComments').val());
                    //$('#lblCommentsNotification').text(savingStatus);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
                    alert('Data provided was not valid');
                }
            });
        }

        //$('#btnSearch').click(function () {


        //});


    });


</script>

MYBUSINESS/Views/SOSR/PerMonthSale.cshtml
@model IEnumerable<MYBUSINESS.Models.SO>
@{
    ViewBag.Title = "Per Month Sale";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<center><h2>Per Month Sale</h2></center>
<center><h4> @ViewBag.ProductName</h4></center>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Month")
        </th>
        <th style="display:none;">
            @Html.DisplayNameFor(model => model.Id)
        </th>

        <th>
            @*@Html.DisplayName("Order No.")*@
            Order No.
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SODs.First().Quantity)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.SODs.First().PurchasePrice)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.SODs.First().SalePrice)
            </th>*@
        <th>
            @Html.DisplayName("Profit")
        </th>

    </tr>
    @{
        string month = string.Empty;
        decimal totProfit = 0;
        decimal monthlyProfit = 0;
        decimal profit = 0;
        int totQty = 0;
        int monthlyQty = 0;
        decimal salePrice = 0;
        foreach (var item in Model)
        {
            if (month == string.Empty)
            {
                month = item.Date.Value.Month.ToString();
            }
            else
            {
                if (month != item.Date.Value.Month.ToString())
                {
                    month = item.Date.Value.Month.ToString();
                    <tr style="font-weight:bold">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>@(monthlyQty)</td>
                        <td>@(monthlyProfit)</td>
                    </tr>
                    monthlyProfit = 0;
                    monthlyQty = 0;
                }
            }


            foreach (var subItem in item.SODs)
            {

                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td style="display:none;">
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.SOSerial)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.Name)
                    </td>

                    <td>
                        @*@Html.DisplayFor(modelSubItem => subItem.Quantity)*@
                        @{

                            monthlyQty += (int)subItem.Quantity;
                            totQty += (int)subItem.Quantity;
                        }
                        @(subItem.Quantity)
                    </td>
                    @*<td>
                            @(subItem.PurchasePrice * subItem.Quantity)
                        </td>*@
                    @*<td>
                            @(subItem.SalePrice * subItem.Quantity)
                        </td>*@

                    <td>
                        @{
                            profit = (decimal)(subItem.SalePrice * subItem.Quantity) - (decimal)(subItem.PurchasePrice * subItem.Quantity);
                            monthlyProfit += profit;
                            totProfit += profit;

                        }
                        @(profit)
                    </td>
                </tr>
            }

        }
        <tr style="font-weight:bold">
            <td></td>
            <td></td>
            <td></td>
            <td>@(monthlyQty)</td>
            <td>@(monthlyProfit)</td>
        </tr>
        <tr style="font-weight:bold">
            <td></td>
            <td></td>
            <td>Total</td>
            <td>@(totQty)</td>
            <td>@(totProfit)</td>
        </tr>
    }
</table>